name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        day: [1]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: list directory
      run: ls -la
      working-directory: "day${{ matrix.day }}"
    - name: Restore dependencies
      run: dotnet restore
      working-directory: "${{ env.GITHUB_WORKSPACE }}/day${{ matrix.day }}/"
    - name: Build
      run: dotnet build --no-restore
      working-directory: "${{ env.GITHUB_WORKSPACE }}/day${{ matrix.day }}/"
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: "${{ env.GITHUB_WORKSPACE }}/day${{ matrix.day }}/"
