name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  determineDays:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: "::set-output name=matrix::$(pwsh ./determineDays.ps)"
    outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
  build:

    runs-on: ubuntu-latest
    needs: determineDays
    strategy:
      matrix:
        day: ${{ fromJson(needs.determineDays.outputs.matrix) }}
    name: "Building Day ${{ matrix.day }}"
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: "day${{ matrix.day }}"
    - name: Build
      run: dotnet build --no-restore
      working-directory: "day${{ matrix.day }}"
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: "day${{ matrix.day }}"
